---
version: '3.7'
services:
  ## Eureka Server
  discovery-server:
    platform: linux/amd64
    image: hanzjk/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  api-gateway:
    platform: linux/amd64
    image: hanzjk/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server


  ## Agora Token-Service Docker Compose Config
  agora-token-server:
    platform: linux/amd64
    container_name: agora-token-server
    pull_policy: always
    image: hanzjk/agora-token-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Avatar-Service Docker Compose Config
  avatar:
    platform: linux/amd64
    container_name: avatar
    pull_policy: always
    image: hanzjk/avatar:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Feedback-Service Docker Compose Config
  feedback:
    platform: linux/amd64
    container_name: feedback
    pull_policy: always
    image: hanzjk/feedback:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Payment-Service Docker Compose Config
  payment:
    platform: linux/amd64
    container_name: payment
    pull_policy: always
    image: hanzjk/payment:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Payment-Service Docker Compose Config
  payment-gateway:
    platform: linux/amd64
    container_name: payment-gateway
    pull_policy: always
    image: hanzjk/payment-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
  ## Stats-Service Docker Compose Config
  stats:
    platform: linux/amd64
    pull_policy: always
    container_name: stats
    image: hanzjk/stats:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Auth-Service Docker Compose Config
  auth:
    platform: linux/amd64
    container_name: auth
    pull_policy: always
    image: hanzjk/auth:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Exhibition-Service Docker Compose Config
  exhibition:
    platform: linux/amd64
    container_name: exhibition
    pull_policy: always
    image: hanzjk/exhibition:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Stall-Service Docker Compose Config
  stall:
    platform: linux/amd64
    container_name: stall
    pull_policy: always
    image: hanzjk/stall:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Ticket-Service Docker Compose Config
  ticket:
    platform: linux/amd64
    container_name: ticket
    pull_policy: always
    image: hanzjk/ticket:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway


